### ISSUE TITLE
Build instructions not working with Debian 12

### ISSUE THREAD

**Issue by jeskko** [RaspSDR/server#23]
Had issues with the following:
- Chroot environment did not have any repositories configured and i had to fix this before the "apk add" line worked, Not 100% sure if the repository configuration below is optimal.
- Apk add -line misses libconfig-static package
- Git submodules need to be initialized/updated 

Got a .bin out of build process after fixing these. Here's a command log that is working for me:

```
sudo apt install qemu-user-static binfmt-support wget
mkdir alpine2
cd alpine2
wget http://dl-cdn.alpinelinux.org/alpine/v3.20/main/armv7/apk-tools-static-2.14.4-r1.apk
mkdir alpine-apk
tar -zxf apk-tools-static-2.14.4-r1.apk --directory=alpine-apk --warning=no-unknown-keyword
mkdir -p alpine-root/usr/bin
cp /usr/bin/qemu-arm-static alpine-root/usr/bin/
mkdir -p alpine-root/etc
cp /etc/resolv.conf alpine-root/etc/
cp -r alpine-apk/sbin alpine-root/
sudo chroot alpine-root /sbin/apk.static --repository http://dl-cdn.alpinelinux.org/alpine/v3.20/main --update-cache --allow-untrusted --initdb add alpine-base
sudo chroot alpine-root /bin/sh --login
cat >/etc/apk/repositories <<EOT
http://dl-cdn.alpinelinux.org/alpine/v3.20/main
http://dl-cdn.alpinelinux.org/alpine/v3.20/community
http://dl-cdn.alpinelinux.org/alpine/edge/testing
EOT
apk update
apk add openssh-server wpa_supplicant wireless-regdb git dhcpcd dnsmasq u-boot-tools hostapd iptables avahi dbus chrony gpsd curl htop frp jq libunwind zlib noip2 noip2-openrc netpbm musl-dev linux-headers g++ gcc cmake make minify fftw-dev fdk-aac-dev pkgconf perl gpsd-dev libunwind-dev zlib-dev sqlite-dev sqlite-static libconfig-static
cd /root
git clone --recurse-submodules https://github.com/raspsdr/server
cd server
mkdir build
cd build
cmake ..
cmake --build .
```

**Comment by howard0su** [comment]
You are right. I miss the step to configure the apk repo. will update it.

**Comment by howard0su** [comment]
fixed

**Comment by jeskko** [comment]
These need a sudo:

```
# echo http://dl-cdn.alpinelinux.org/alpine/v3.20/main > alpine-root/etc/apk/repositories
# echo http://dl-cdn.alpinelinux.org/alpine/v3.20/community >> alpine-root/etc/apk/repositories
```

Something like this:

```
# echo http://dl-cdn.alpinelinux.org/alpine/v3.20/main | sudo tee alpine-root/etc/apk/repositories
# echo http://dl-cdn.alpinelinux.org/alpine/v3.20/community | sudo tee -a alpine-root/etc/apk/repositories
```

This is still missing from the apk add command and final linking fails:

```
# apk add libconfig-static
```
